//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace first.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int id { get; set; }
        public int booking_id { get; set; }
        public decimal room_charges { get; set; }
        public Nullable<decimal> other_charges { get; set; }
        public decimal total_amount { get; set; }
        public Nullable<System.DateTime> generated_at { get; set; }
        public string status { get; set; }
    
        public virtual booking booking { get; set; }
    }
}
