//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace first.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class expens
    {
        public int id { get; set; }
        [Required]
        public string category { get; set; }
        public Nullable<int> inventory_id { get; set; }
        [Required]
        public string item_name { get; set; }
        public string description { get; set; }
        public decimal amount { get; set; }
        public System.DateTime expense_date { get; set; }
        public Nullable<int> recorded_by { get; set; }
    
        public virtual inventory inventory { get; set; }
        public virtual user user { get; set; }
    }
}
