//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace first.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class feedback
    {
        public int id { get; set; }
        [Required]
        public string message { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public int booking_id { get; set; }
        [Required]
        public int rating { get; set; }
    
        public virtual booking booking { get; set; }
    }
}
