//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace first.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseKeeping_duties
    {
        public int id { get; set; }
        public int room_id { get; set; }
        public int assigned_to { get; set; }
        public string status { get; set; }
        public string issue_reported { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual user user { get; set; }
        public virtual room room { get; set; }
    }
}
